name: Context Demo
on: workflow_dispatch
env:
  workflow-level: Bakr
  
jobs: 
  print-some-stuff:
    runs-on: ubuntu-latest
    env:
      job-level: ruben

      strategy:
        matrix:
          colour: [red, blue, green]
          number: [1,2,3]
    steps:
      - name: setup another env var
        env:
          another-step: secret
        run: echo ${{ env.another-step }}
      - name: print som context 
        env:
          this-step: demelza
        run: |
          echo "Hello world, from our workflow"
          echo "our env i: ${{ toJson(env) }}"
          echo "out vars i: ${{ toJson(vars) }}"
          
          

      - name: matrix timeout-minutes
        run: |
          echo "our matrix is: ${{ toJson(matrix) }}"
