name: Context Demo

on: workflow_dispatch

jobs: 
  print-some-stuff:
    runs-on: ubuntu-slim
    steps:
      - name: print som context 
        run: |
          echo "Hello world, from our workflow"
          echo "our env i: ${{ toJson(env) }}"
          echo "out vars i: ${{ toJson(vars) }}"
          echo "our matrix i: ${{ toJson(matrix) }}"
          
        
