name: Context Demo
on: workflow_dispatch
env:
  workflow-level: Bakr
  website: mindfulstack.se
  
jobs: 
  print-some-stuff:
    runs-on: ubuntu-latest
    env:
      job-level: ruben

    strategy:
      matrix:
        colour: [red, blue, green]
        name: [Bakr, Ruben, Demelza]

    steps:
      - name: setup another env var
        env:
          secret: 42
        run: |
          echo "with gh expression syntax: ${{ env.secret }}"
          echo "with pure bash: $secret"

      - name: print som context 
        env:
          this-step: demelza
        run: |
          echo "Hello world, from our workflow"
          echo "our env i: ${{ toJson(env) }}"
          echo "out vars i: ${{ toJson(vars) }}"
          
      - name: matrix timeout-minutes
        run: |
          echo "our matrix is: ${{ toJson(matrix) }}"
          echo "${{ matrix.name}}s favourite color is ${{matrix.colour}}"
          
