name: Env Context Demo
on: workflow_dispatch

env:
  workflow_level: "jag är satt på workflow-nivå"

jobs:
  visa-env:
    runs-on: ubuntu-latest        
    env:
      job_level: "jag är satt på job-nivå"
    steps:
      - name: Steg 1
        env:
          step_level: "jag är satt på step-nivå"
        run: |
          echo "Workflow: $workflow_level"
          echo "Job: $job_level"
          echo "Step: $step_level"

      - name: Steg 2
        run: |
          echo "Workflow: $workflow_level"
          echo "Job: $job_level"
          echo "Step (borde vara tom!): $step_level"
